# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  pull_request:
    branches:
      - release/v[0-9]+.[0-9]+.[0-9]+

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run test
        run: |
          make test
