name: Test

on:
  pull_request:
    branches:
      - master
      - release/v[0-9]+.[0-9]+.[0-9]+
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ready for review
        if: github.event.pull_request.draft == true
        run: |
          echo "PR isn't ready for review. Workflow won't run before it."
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          make test
