name: Test

on:
  pull_request:
    branches:
      - master
      - release/v[0-9]+.[0-9]+.[0-9]+
    types: [review_requested, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          make test
