name: Verify

on:
  pull_request:
    branches:
      - master
    types: [review_requested, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: check
        name: Verify if version updated
        uses: EndBug/version-check@v1
        with:
          file-url: https://raw.githubusercontent.com/DZakh-packages/eslint-plugin-clean-css-modules/master/package.json
          static-checking: localIsNew

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'
